#'#' GMClassification
#'
#' This function retrieves gene module classifications using cell module score columns in seurat object.
#'
#' @param seurat_obj Seurat object
#' @param group_by column to group cells by, classification or clusters are recommended
#' @param plot_path Directory to plot log files
#' @param gene_modules List of gene modules generated by antler package
#' @param rotated_labels boolean value to specify whether to rotate x axis labels in classification boxplots
#' @return dataframe of gene modules and their classifications
#' @export

GMClassification <- function(seurat_obj = seurat_data, gene_modules = antler_data$gene_modules$lists$unbiasedGMs_DE$content, 
                             assay = 'RNA', plot_path = "scHelper_log/", group_by = "scHelper_cell_type") 
{
  dir.create(plot_path, recursive = TRUE, showWarnings = FALSE)
  
  metrics = names(gene_modules)
  
  DefaultAssay(seurat_obj) <- assay
  
  temp_seurat <- seurat_obj
  
  # Calculate average module expression for contamination gene list
  temp_seurat <- AverageGeneModules(seurat_obj = temp_seurat, gene_list = gene_modules)
  
  png(paste0(plot_path, "gm_classification.png"), width = 40, height = 30, units = "cm", res = 200)
  grid.arrange(grobs = lapply(metrics, function(x) {
    p = BoxPlot(dat = temp_seurat@meta.data, y_col = x, group_by = group_by, 
                y_lab = x, x_lab = group_by, rotated_labels = rotated_labels) }) )
  graphics.off()
  
  # select clusters and cell type annotations which are higher than percentile threshold
  celltype_df = temp_seurat@meta.data %>%
    dplyr::select(c(!!as.symbol(group_by), all_of(metrics))) %>%
    reshape2::melt() %>%
    mutate(variable = as.character(variable))
  
  # Add median gene module scores for each cell cluster
  celltype_df = celltype_df %>%
    group_by(!!as.symbol(group_by), variable, .drop = FALSE) %>%
    mutate(median = median(value)) %>%
    group_by(variable, .drop = FALSE) %>%
    mutate(median_percentile = ecdf(value)(median))
  
  # Drop individual cell gene module scores and remove duplicate rows
  celltype_df = celltype_df %>%
    dplyr::select(!value) %>%
    distinct(.keep_all = TRUE)
  
  # Select top classification for each cluster
  celltype_df = celltype_df %>%
    group_by(variable) %>% 
    top_n(1, median_percentile) %>%
    dplyr::select(c(!!as.symbol(group_by), variable))
  
  colnames(celltype_df) <- c("group_by", "gene_module")
  return(celltype_df)
}