name: docker-build-push
#https://github.com/marketplace/actions/build-and-push-docker-images

on:
  push:
    branches: 
      - main
    paths: 
      - '**/Dockerfile'

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        docker-file: ["Dockerfile"]
        module-name: ["base", "dependencies"]

    steps:
      - uses: actions/checkout@v2
      - name: Set version and tags
        id: ver
        run: |
          VERSION=`cat containers/VERSION`
          echo "version: $VERSION"
          echo "::set-output name=version::$(echo $VERSION)"
        shell: bash
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexthiery/scHelpr
          path: containers/${{matrix.module-name}}
          dockerfile: containers/${{matrix.module-name}}/Dockerfile
          tags: ${{matrix.module-name}}-${{steps.ver.outputs.version}}
